version: "3.9"

services:
  auth-service:
    build: ./apps/auth-service
    ports:
      - "3001:3001"
    env_file: .env
    depends_on:
      - postgres
    networks:
      - nest-net

  product-service:
    build: ./apps/product-service
    ports:
      - "3002:3002"
    env_file: .env
    depends_on:
      - postgres
    networks:
      - nest-net

  order-service:
    build: ./apps/order-service
    ports:
      - "3003:3003"
    env_file: .env
    depends_on:
      - postgres
    networks:
      - nest-net

  # optional API Gateway
  # api-gateway:
  #   build: ./apps/api-gateway
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - auth-service
  #     - product-service
  #     - order-service
  #   networks:
  #     - nest-net

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: nestuser
      POSTGRES_PASSWORD: nestpass
      POSTGRES_DB: youshop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - nest-net

networks:
  nest-net:

volumes:
  pgdata:
